export const CBS_CONSTANTS = {
  TIMEOUTS: {
    SHORT: 5_000,
    MEDIUM: 15_000,
    LONG: 30_000,
    EXTRA_LONG: 60_000,
  },
  PAGINATION: {
    DEFAULT_PAGE_SIZE: 10,
    MAX_PAGE_SIZE: 100,
  },
  VALIDATION: {
    PAN_REGEX: /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/,
    AADHAAR_REGEX: /^\d{12}$/,
    MOBILE_REGEX: /^[6-9]\d{9}$/,
    IFSC_REGEX: /^[A-Z]{4}0[A-Z0-9]{6}$/,
    ACCOUNT_NUMBER_MIN_LENGTH: 9,
    ACCOUNT_NUMBER_MAX_LENGTH: 18,
  },
  MESSAGES: {
    SAVE_SUCCESS: 'Record saved successfully',
    UPDATE_SUCCESS: 'Record updated successfully',
    DELETE_SUCCESS: 'Record deleted successfully',
    AUTHORIZE_SUCCESS: 'Record authorized successfully',
    VALIDATION_ERROR: 'Please correct the highlighted errors',
    SESSION_EXPIRED: 'Your session has expired',
  },
  ROUTES: {
    DASHBOARD: '/dashboard',
    CUSTOMER_CREATION: '/customer/create',
    CUSTOMER_MODIFICATION: '/customer/modify',
    CUSTOMER_INQUIRY: '/customer/inquiry',
    ACCOUNT_OPENING: '/account/open',
    ACCOUNT_MODIFICATION: '/account/modify',
    ACCOUNT_CLOSURE: '/account/close',
    FIXED_DEPOSIT: '/deposit/fixed',
    RECURRING_DEPOSIT: '/deposit/recurring',
    LOAN_CREATION: '/loan/create',
    LOAN_DISBURSEMENT: '/loan/disburse',
    RTGS_ENTRY: '/remittance/rtgs',
    NEFT_ENTRY: '/remittance/neft',
    IMPS_ENTRY: '/remittance/imps',
  },
} as const;
